version: "3.9"

services:

  web:
    build: flask-app/
    container_name: web
    volumes: 
      - './flask-app:/code'
      - './secrets:/secrets'
    restart: unless-stopped
    ports:
      - "8001:4000"
    links:
      - db

  db:
    image: mysql:8
    container_name: db
    volumes:
      - './db:/docker-entrypoint-initdb.d/:ro'
    ports:
      - "3200:3306"
    restart: unless-stopped
    environment: 
      MYSQL_DATABASE : Magic
      MYSQL_USER: webapp

      MYSQL_PASSWORD_FILE: /run/secrets/secret_db_pw
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/secret_db_root_pw
    secrets:
      - secret_db_pw
      - secret_db_root_pw

  ##################################################################
  # configure the AppSmith container (borrowed directly from Appsmith)
  appsmith:
    image: index.docker.io/appsmith/appsmith-ce
    container_name: appsmith
    ports:
      - "8080:80"
      - "4443:443"
    volumes:
      - ./stacks:/appsmith-stacks
    restart: unless-stopped

secrets:
  secret_db_pw:
    file: ./secrets/db_password.txt
  secret_db_root_pw:
    file: ./secrets/db_root_password.txt
